import { useState } from 'react';

const Cards = () => {
    const cardSection = {
        title: 'Sample Books Generated by BookAI',
        description: 'Explore some of the captivating books created using our AI technology.',
        cards: [
            { id: 1, image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png', title: 'Science Fiction', description: 'As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands ...' },
            { id: 2, image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png', title: 'Mystery', description: 'The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light ...' },
            { id: 3, image: 'https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png', title: 'Fantasy', description: 'The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath ...' },
        ],
    };

    return (
        <div className="flex flex-col items-center pb-6 w-[80%] mx-auto">
            <header className="text-center mb-8">
                <h1 className="text-3xl font-bold mb-4 text-gray-400 hover:text-white transition-colors duration-300">{cardSection.title}</h1>
                <p className="text-lg text-gray-400 hover:text-white transition-colors duration-300">{cardSection.description}</p>
            </header>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {cardSection.cards.map(card => (
                    <Card key={card.id} {...card} />
                ))}
            </div>
        </div>
    );
};

const Card = ({ image, title, description }) => {
    const [isReadMore, setIsReadMore] = useState(false);
    const toggleReadMore = () => setIsReadMore(!isReadMore);
    const maxLength = 100;

    return (
        <div className="shadow-md rounded-lg overflow-hidden bg-[#FFFFFF0D] p-5 transform transition-transform duration-300 hover:-translate-y-2">
    <img src={image} alt={title} className="h-96 rounded-lg mx-auto" />
    <div className="p-4 flex flex-col justify-center items-center">
        <h3 className="text-2xl font-semibold mb-2 text-gray-300 hover:text-white transition-colors duration-300">
            {title}
        </h3>
        <p className="text-gray-400 text-lg text-center italic transition-colors duration-300">
            {description.length > maxLength 
                ? `"${isReadMore ? description : `${description.substring(0, maxLength)}...`}"`
                : description}
        </p>
        {description.length > maxLength && (
            <button 
                onClick={toggleReadMore} 
                className="text-[#8a2be2] hover:text-white cursor-pointer mt-2 transition-colors duration-300"
            >
                {isReadMore ? ' Show Less' : ' Read More'}
            </button>
        )}
    </div>
</div>

    );
};

export default Cards;
